participants:

    Calculix:
        interfaces:
        - nodes-mesh: Solid-Mesh
          patch: interface
          read-data: [Forces]
          write-data: [Displacements]
          
precice-config-file: ../precice-config.xml